name: juragan99
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.20
  smooth_star_rating: ^1.1.1
  image_picker: ^0.8.4+10
  fluttertoast: ^7.1.5
  flutter_svg: ^0.19.0
  dropdown_search: ^0.5.0
  ticket_card: ^0.2.0
  intl: ^0.17.0
  hexcolor: ^2.0.6
  flutter_custom_tab_bar: ^1.1.9
  flutter_swiper: ^1.1.6
  dotted_line: ^3.1.0
  dio: ^4.0.4
  http: ^0.13.4
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.8.1
  cached_network_image: ^2.5.1
  flutter_datetime_picker: 
    git: https://github.com/Realank/flutter_datetime_picker.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboard/
    - assets/svg/
    - assets/images/bus/
    - assets/images/icon/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/j99-icon.png"